baseURL = "https://blog.opubliq.com/"
defaultContentLanguage = "fr"
theme = "congo"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
